"""Liveness, readiness and RBAC-introspection endpoints.

Azure App Service, Kubernetes and every other scheduler need two different
answers, and conflating them causes outages:

``/health/live``
    Is the process running?  Never touches a dependency.  A liveness probe
    that fails because a *downstream* service is down gets the healthy process
    restarted, which helps nobody.

``/health/ready``
    Should this instance receive traffic?  Checks the database, and reports
    on the JWKS cache without forcing a fetch.

``/health/rbac``
    Which permission does each route actually require?  Generated by walking
    the live URL map, so it reflects the decorators rather than a document
    that drifted away from them.  This is the fastest way to confirm that the
    Auth0 role configuration and the code agree.
"""

from __future__ import annotations

import os
import platform
from typing import Any, Dict, List

from flask import Blueprint, current_app, jsonify
from sqlalchemy import text

from .auth.auth import jwks_cache
from .database.models import db

health_bp = Blueprint("health", __name__)

#: Bumped by hand; surfaced so a deployed instance can be identified.
API_VERSION = "1.0.0"


@health_bp.route("/health/live", methods=["GET"])
def liveness():
    """Report that the process is up.  Checks nothing else, by design."""
    return jsonify({"success": True, "status": "alive"}), 200


@health_bp.route("/health/ready", methods=["GET"])
def readiness():
    """Report whether this instance can serve traffic."""
    checks: Dict[str, Any] = {}
    ready = True

    try:
        db.session.execute(text("SELECT 1"))
        checks["database"] = {"ok": True}
    except Exception as exc:  # noqa: BLE001 - the reason is the payload
        db.session.rollback()
        ready = False
        checks["database"] = {"ok": False, "error": type(exc).__name__}

    # Reported, not probed: forcing a JWKS fetch on every readiness check
    # would hand a load balancer the ability to rate-limit us out of Auth0.
    checks["jwks_cache"] = jwks_cache.stats()

    checks["auth0_configured"] = {
        "ok": bool(
            current_app.config.get("AUTH0_DOMAIN")
            and current_app.config.get("AUTH0_API_AUDIENCE")
        )
    }
    if not checks["auth0_configured"]["ok"]:
        ready = False

    return (
        jsonify(
            {
                "success": ready,
                "status": "ready" if ready else "degraded",
                "checks": checks,
            }
        ),
        200 if ready else 503,
    )


@health_bp.route("/health", methods=["GET"])
def health():
    """Summarise the service: version, runtime and configuration shape.

    Deliberately free of anything an attacker could use -- no secrets, no
    connection strings, no tenant credentials.  The Auth0 domain is public
    information (the frontend redirects a browser to it), and the audience is
    printed in every token.
    """
    return (
        jsonify(
            {
                "success": True,
                "status": "ok",
                "service": "coffee-shop-api",
                "version": API_VERSION,
                "python": platform.python_version(),
                "environment": os.environ.get("FLASK_CONFIG", "development"),
                "auth0": {
                    "domain": current_app.config.get("AUTH0_DOMAIN"),
                    "audience": current_app.config.get("AUTH0_API_AUDIENCE"),
                    "algorithms": current_app.config.get("AUTH0_ALGORITHMS"),
                },
                "features": {
                    "user_administration": current_app.config.get(
                        "MANAGEMENT_API_ENABLED", False
                    ),
                    "rate_limiting": current_app.config.get("RATELIMIT_ENABLED", False),
                    "audit_log": current_app.config.get("AUDIT_LOG_ENABLED", False),
                    "docs": current_app.config.get("DOCS_ENABLED", False),
                },
            }
        ),
        200,
    )


@health_bp.route("/health/rbac", methods=["GET"])
def rbac_matrix():
    """Return the live route-to-permission map.

    Built by walking Flask's URL map and reading the ``required_permission``
    attribute that :func:`~src.auth.auth.requires_auth` stamps onto each view,
    so it cannot fall out of step with the code the way a hand-written table
    would.
    """
    if not current_app.config.get("DOCS_ENABLED", True):
        return (
            jsonify({"success": False, "error": 404, "message": "resource not found"}),
            404,
        )

    routes: List[Dict[str, Any]] = []
    for rule in current_app.url_map.iter_rules():
        if rule.endpoint == "static":
            continue
        view = current_app.view_functions.get(rule.endpoint)
        permission = getattr(view, "required_permission", None)
        methods = sorted(rule.methods - {"HEAD", "OPTIONS"})
        if not methods:
            continue
        routes.append(
            {
                "rule": str(rule),
                "methods": methods,
                "endpoint": rule.endpoint,
                # None  -> the decorator is absent entirely (public route)
                # ""    -> any valid token, no specific permission
                "permission": permission,
                "public": permission is None,
            }
        )

    routes.sort(key=lambda item: (item["rule"], item["methods"]))

    from .management.users_api import ROLE_RANKS

    return (
        jsonify(
            {
                "success": True,
                "routes": routes,
                "roles": [
                    {"name": name.title(), "rank": rank}
                    for name, rank in sorted(
                        ROLE_RANKS.items(), key=lambda item: item[1]
                    )
                ],
                "note": (
                    "permission=null means no authentication is required; "
                    'permission="" means any valid token is accepted.'
                ),
            }
        ),
        200,
    )
